global:
  scrape_interval: 2s
  evaluation_interval: 2s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Node Exporter - CPU/RAM/Disk/Network host
  - job_name: "node"
    static_configs:
      - targets: ["node_exporter:9100"]

  # Blackbox - Website UP/DOWN (dynamic target discovery via file_sd_configs)
  - job_name: "blackbox_http"
    metrics_path: /probe
    params:
      module: [http_2xx]
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/websites.yml
        refresh_interval: 2s
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
